# Generated by Django 4.2.3 on 2023-08-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                verbose_name="номер телефона",
            ),
        ),
    ]
