# Generated by Django 4.2.3 on 2023-08-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="пароль"
            ),
        ),
    ]
