# Generated by Django 4.2.3 on 2023-08-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0007_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.IntegerField(null=True, verbose_name="Проверочный код"),
        ),
    ]
